### ISSUE TITLE
[FEAT] UI 사이즈 설정, githubService 공유

### ISSUE THREAD

**Issue by 2unbini** [42Caterpie/git-challengers-ios#13]
## 📌  Feature Issue
UI 사이즈 설정
githubService 하위 뷰에 공유(EnvironmentObject)

## 📝  To-do

- [x] UIScreen으로 전체 사이즈 설정
- [x] cardModifier 수정
- [x] githubService 하위 뷰에 공유
- [x] 기타 Modifier 파일로 분리

## Tested
iPhone 11 Pro iOS 15.0, 13.0
